### ISSUE TITLE
Video not downloading

### ISSUE THREAD

**Issue by hashirnouman** [iqbal-rashed/ytdlp-nodejs#1]
when I run my index file the terminal throws the following error
`node:internal/process/promises:288███████████████████████████░░░░░ 86% | 4s remaining...Bin file downloaded completed, please restar            triggerUncaughtException(err, true /* fromPromise */);
            ^eg-win64.zip ████████████████████████████████████████ 100% | 0s remaining...

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "ENOENT: no such file or directory, open 'E:\ytdl\node_modules\__bin\ffmpeg-win64.zip'".] {`

**Comment by alands-offc** [comment]
> when I run my index file the terminal throws the following error `node:internal/process/promises:288███████████████████████████░░░░░ 86% | 4s remaining...Bin file downloaded completed, please restar triggerUncaughtException(err, true /* fromPromise */); ^eg-win64.zip ████████████████████████████████████████ 100% | 0s remaining...
> 
> [UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "ENOENT: no such file or directory, open 'E:\ytdl\node_modules__bin\ffmpeg-win64.zip'".] {`

npm install ffmpeg and apt install ffmpeg
