### ISSUE TITLE
Incorrect paths for YtDlp for platforms other than Windows x64

### ISSUE THREAD

**Issue by adampisula** [iqbal-rashed/ytdlp-nodejs#3]
In `src/utils/binfile.ts` in function `getBinPath()`, the ytdlp executable path is not being assigned correctly. On  lines 42, 48 and 51 you used comparison instead of assignment (`==` instead of `=`). This causes it to error out.

**Comment by adampisula** [comment]
@iqbal-rashed  Please remember to republish the NPM package :)

**Comment by iqbal-rashed** [comment]
Published
